apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: cbe3lxoy7-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-c56fe63351.i9ps.p3.openshiftapps.com/rhtap/rhtap-qe-go:25beb54dfa07664a31491da07a506d27cdcb8044@sha256:e663508ae44231c211133c89a70f8663a4fb4bdf4fe65e9a31810992e9c3130c
          name: container-image
